src/Web/Models/HomeViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;

namespace Web.Models
{
    public class HomeViewModel
    {
        public List<ProductViewModel> Products { get; set; }

        public List<SelectListItem> Brands { get; set; }

        public List<SelectListItem> Categories { get; set; }

        public int? BrandId { get; set; }

        public int? CategoryId { get; set; }

        public PaginationInfoViewModel PaginationInfo { get; set; }
    }
}

src/Web/Controllers/BasketController.cs
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web.Interfaces;
using Web.Models;

namespace Web.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketViewModelService _basketViewModelService;

        public BasketController(IBasketViewModelService basketViewModelService)
        {
            _basketViewModelService = basketViewModelService;
        }

        public async Task<IActionResult> Index()
        {
            var basketViewModel = await _basketViewModelService.GetBasketViewModelAsync();
            return View(basketViewModel);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(Dictionary<int, int> quantities)
        {
            if (quantities.Values.Any(x => x < 1))
            {
                TempData["error"] = "We have encountered a problem updating the quantities.";
                return RedirectToAction(nameof(Index));
            }

            var basket = await _basketViewModelService.SetQuantitiesAsync(quantities);
            TempData["message"] = "Items updated successfully";
            return View(basket);
        }

        [HttpPost]
        public async Task<IActionResult> AddItem(int productId, int quantity = 1)
        {
            if (quantity < 1)
            {
                return BadRequest();
            }

            int totalItems = await _basketViewModelService.AddItemToBasketAsync(productId, quantity);
            return Json(new { totalItems });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> EmptyBasket()
        {
            await _basketViewModelService.DeleteBasketAsync();
            TempData["message"] = "All items removed from cart successfully";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveItem(int itemId)
        {
            await _basketViewModelService.DeleteBasketItemAsync(itemId);
            TempData["message"] = "Item removed from cart successfully";
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public async Task<IActionResult> Checkout()
        {
            var basket = await _basketViewModelService.GetBasketViewModelAsync();
            var vm = new CheckoutViewModel();
            vm.Basket = basket;
            return View(vm);
        }

        [Authorize]
        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Checkout(CheckoutViewModel vm)
        {
            if (ModelState.IsValid)
            {
                var address = new Address()
                {
                    City = vm.City,
                    Country = vm.Country,
                    State = vm.State,
                    Street = vm.Street,
                    ZipCode = vm.ZipCode
                };
                var order = await _basketViewModelService.CompleteCheckoutAsync(address);
                return RedirectToAction(nameof(OrderComplete), new { orderId = order.Id });
            }

            vm.Basket = await _basketViewModelService.GetBasketViewModelAsync();
            return View(vm);
        }

        [Authorize]
        public async Task<IActionResult> OrderComplete(int orderId)
        {
            return View(orderId);
        }
    }
}

src/Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Web.Interfaces;
using Web.Models;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IHomeViewModelService _homeViewModelService;

        public HomeController(ILogger<HomeController> logger, IHomeViewModelService homeViewModelService)
        {
            _logger = logger;
            _homeViewModelService = homeViewModelService;
        }

        public async  Task<IActionResult> Index(int? brandId, int? categoryId, int pageId = 1)
        {
            return View(await _homeViewModelService.GetHomeViewModelAsync(brandId, categoryId, pageId));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Web/Views/Home/Index.cshtml
@model HomeViewModel
@{
    ViewData["Title"] = "Home Page";
    var pi = Model.PaginationInfo;
}

<h1>Products</h1>

<div class="border rounded bg-light p-2">
    <form class="form-inline" method="get">
        <label class="mr-sm-2 mb-sm-0 mb-2">Brand</label>
        <select asp-for="BrandId" asp-items="Model.Brands" class="form-control mr-sm-2 mb-sm-0 mb-2">
        </select>
        <label class="mr-sm-2 mb-sm-2 mb-2">Category</label>
        <select asp-for="CategoryId" asp-items="Model.Categories" class="form-control mr-sm-2 mb-sm-0 mb-2">
        </select>
        <button class="btn btn-primary mb-sm-0">List</button>
    </form>
</div>

<div class="row mt-3">
    @foreach (var product in Model.Products)
    {
        <div class="col-6 col-md-4 col-lg-3 mb-4">
            <div class="card">
                <div class="card-body">
                    <img class="w-100" src="~/img/products/@product.PictureUri" alt="@product.Name" />
                    <div class="product-name mt-2" title="@product.Name">@product.Name</div>
                    <div class="mt-3 d-flex justify-content-between">
                        <div>@product.PriceTry</div>
                        <a data-add-item-to-basket="@product.Id" class="btn btn-sm btn-success" data-toggle="tooltip" data-placement="top" title="Add to Basket">
                            <i class="fa-solid fa-lg fa-cart-plus"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<hr />

<div class="text-center mt-3">
    Showing @pi.DisplayStart to @pi.DisplayEnd of @pi.TotalItems products
</div>

<nav class="d-flex justify-content-center mt-2">
    <ul class="pagination">
        @if (pi.HasPrevious)
        {
            <li class="page-item">
                <a class="page-link" asp-route-brandId="@Model.BrandId" asp-route-categoryId="@Model.CategoryId" asp-route-pageId="@(pi.CurrentPage - 1)">&laquo;</a>
            </li>
        }
        else
        {
            <li class="page-item disabled"><a class="page-link" href="#">&laquo;</a></li>
        }

        @foreach (var i in pi.PageNumbers)
        {
            if (i == -1)
            {
                <li class="page-item disabled">
                    <a tabindex="-1" href="#" class="page-link">&hellip;</a>
                </li>
            }
            else
            {
                <li class="page-item @(i == pi.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-route-brandId="@Model.BrandId" asp-route-categoryId="@Model.CategoryId" asp-route-pageId="@i">@i</a>
                </li>
            }
        }
        @if (pi.HasNext)
        {
            <li class="page-item">
                <a class="page-link" asp-route-brandId="@Model.BrandId" asp-route-categoryId="@Model.CategoryId" asp-route-pageId="@(pi.CurrentPage + 1)">&raquo;</a>
            </li>
        }
        else
        {
            <li class="page-item disabled"><a class="page-link" href="#">&raquo;</a></li>
        }

    </ul>
</nav>

@section Scripts {
    <script>
        $("[data-add-item-to-basket]").click(function (event) {
            event.preventDefault();
            const id = $(this).data("add-item-to-basket");
            $.ajax({
                url: "@Url.Action("AddItem", "Basket")",
                type: "POST",
                data: { productId: id },
                success: function (data) {
                    $("#navBasketItemCount").text(data.totalItems);
                    successMessage("Item successfully added to your cart");
                }
            });
        });
    </script>
}